---
name: Compile

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '**.mq[45h]'
      - '.github/workflows/compile.yml'
  push:
    paths:
      - '**.mq[45h]'
      - '.github/workflows/compile.yml'

jobs:
  Compile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: EA31337/EA31337-classes
      - uses: fx31337/mql-compile-action@master
        with:
          path: .
          verbose: true
